### ISSUE TITLE
Automate build of SPA

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#37]
steps in #28 should be automated via an sbt task

**Comment by neelsmith** [comment]
Define an `spa` task that depends on `fullOptJS`.  It should:

1. Cp  `src/main/resources/cite-VERSION.html`  to a new file appropriately named using the current version setting
2. Read in css and js from the build files, and replace place-holder strings wtih their full values

**Comment by Eumaeus** [comment]
Here is what I do when I do this manually:

- In the file `cite-1.1.0.html` (which lives at `src/main/resources/` and gets copied to `target/classes/`)…
- paste the entire contents of `application.css` between the `<style></style>` elements (i.e. after line 6).
- Delete the last line of `citeapp-opt.js` (the `.js.map` file). If you don't the browser will throw console errors because it can't find that file.
- Paste `citeapp-opt.js` between the `<script type="text/javascript"></script>` tags in `cite-1.1.0.html` (i.e. after line 11).

**Comment by Eumaeus** [comment]
Seems like more of a shell-script thing than an SBT thing.

**Comment by neelsmith** [comment]
I'm going to define an `spa` task that does everything.

`sbt spa` will fastOpt compile, and assemble an appropirately named SPA file.  Stay tuned --I'm giving an exam today, so may have an hour to work on this.

**Comment by neelsmith** [comment]
implemented
